config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,:email,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReFormer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :name %> <br/> <!-- when the form is submitted, the value entered by the user will be available in the controller as params[:user][:name]. -->
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %> <br/>
    <%= f.text_field :email, :value => "example@email.com" %>
  </p>
  <p>
    <%= f.label :password %> <br/>
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit %></p>

<% end %>

<!-- HTML and #form_tag forms (which should still be commented out) will not work -- they will submit the form as a POST request when you need it to be a PATCH (PUT) -->

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User</th>
    <th>Email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to "edit", edit_user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<!-- <!DOCTYPE html>
<html>
<body>
  <form method="post" action="/users" accept-charset="UTF-8">
    Username:  <input type="text" name="user[name]" value=""><br>
    Email:     <input type="text" name="user[email]" value=""><br>
    Password: <input type="password" name="user[password]" value=""><br>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Save Changes">
  </form>
</body>
</html> -->
<!--<%= form_tag("/users",method: "post") do %>
  <%= text_field_tag(:name) %><br>
  <%= text_field_tag(:email) %><br>
  <%= password_field_tag(:password) %><br>
  <%= submit_tag "Submit" %>
<% end %>-->

<%= form_for(@user) do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :name %> <br/> <!-- when the form is submitted, the value entered by the user will be available in the controller as params[:user][:name]. -->
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %> <br/>
    <%= f.text_field :email, :value => "example@email.com" %>
  </p>
  <p>
    <%= f.label :password %> <br/>
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit %></p>

<% end %>